name: fasting_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Updated to a more standard constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # CORRECTED: Locked to a stable version
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1 # Updated to more recent stable versions
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^5.4.4 # Kept your downgraded version
  flutter_local_notifications: ^19.4.2 # Updated
  timezone: ^0.10.1
  permission_handler: ^12.0.1 # Updated
  flutter_background_service: ^5.0.1
  fl_chart: ^1.1.1 # Updated
  provider: ^6.0.5
  shared_preferences: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 # Moved to dev_dependencies (best practice)
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    # REMOVED: "- lib/l10n/" is not an asset

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fasting_app.png"
  min_sdk_android: 21