// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdROWxopNiwurgOAeRdIpWplMuxZAgq0Y',
    appId: '1:1011646303665:web:9c8992df314722ca47c190',
    messagingSenderId: '1011646303665',
    projectId: 'fasting-tracker-app-78f8c',
    authDomain: 'fasting-tracker-app-78f8c.firebaseapp.com',
    storageBucket: 'fasting-tracker-app-78f8c.firebasestorage.app',
    measurementId: 'G-Q5JQBTL5N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOrPzefkVb2fDzf29m2mqLbZMgGWNUfsE',
    appId: '1:1011646303665:android:d99fc4b7badd368747c190',
    messagingSenderId: '1011646303665',
    projectId: 'fasting-tracker-app-78f8c',
    storageBucket: 'fasting-tracker-app-78f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVoJyY0s6XzaqXipyay2FJgu_-5Xem3A',
    appId: '1:1011646303665:ios:95ebf70cf6f06c6047c190',
    messagingSenderId: '1011646303665',
    projectId: 'fasting-tracker-app-78f8c',
    storageBucket: 'fasting-tracker-app-78f8c.firebasestorage.app',
    iosBundleId: 'com.example.fastingTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVoJyY0s6XzaqXipyay2FJgu_-5Xem3A',
    appId: '1:1011646303665:ios:95ebf70cf6f06c6047c190',
    messagingSenderId: '1011646303665',
    projectId: 'fasting-tracker-app-78f8c',
    storageBucket: 'fasting-tracker-app-78f8c.firebasestorage.app',
    iosBundleId: 'com.example.fastingTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdROWxopNiwurgOAeRdIpWplMuxZAgq0Y',
    appId: '1:1011646303665:web:5c8c2468a501b10d47c190',
    messagingSenderId: '1011646303665',
    projectId: 'fasting-tracker-app-78f8c',
    authDomain: 'fasting-tracker-app-78f8c.firebaseapp.com',
    storageBucket: 'fasting-tracker-app-78f8c.firebasestorage.app',
    measurementId: 'G-DMEGXGQK5R',
  );
}
